# Generated by Django 2.2.7 on 2019-12-07 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cpf', models.CharField(help_text='EX.: 99999999999', max_length=11)),
                ('idade', models.IntegerField()),
                ('telefone1', models.CharField(help_text='EX.:(99)99999-9999', max_length=14)),
                ('telefone2', models.CharField(blank=True, help_text='EX.:(87)3333-3333', max_length=13, null=True)),
                ('img', models.ImageField(blank=True, help_text='Tamanho máximo 50x50', null=True, upload_to='', verbose_name='Imagem')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(help_text='Nome do Delivery: ', max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('cnpj', models.CharField(help_text='99.999.999/9999-99', max_length=18, verbose_name='CNPJ')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('telefone1', models.CharField(help_text='EX.:(99)99999-9999', max_length=14)),
                ('telefone2', models.CharField(blank=True, help_text='EX.:(87)3333-3333', max_length=13, null=True)),
                ('img', models.ImageField(blank=True, help_text='Tamanho máximo 50x50', null=True, upload_to='', verbose_name='Imagem')),
                ('is_ativo', models.BooleanField(default=False, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': "Delivery's",
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Rondônia', 'Rondônia'), ('Acre', 'Acre'), ('Amazonas', 'Amazonas'), ('Roraima', 'Roraima'), ('Pará', 'Pará'), ('Amapá', 'Amapá'), ('Tocantins', 'Tocantins'), ('Maranhão', 'Maranhão'), ('Piauí', 'Piauí'), ('Ceará', 'Ceará'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Paraíba', 'Paraíba'), ('Pernambuco', 'Pernambuco'), ('Alagoas', 'Alagoas'), ('Sergipe', 'Sergipe'), ('Bahia', 'Bahia'), ('Minas Gerais', 'Minas Gerais'), ('Espírito Santo', 'Espírito Santo'), ('Rio de Janeiro', 'Rio de Janeiro'), ('São Paulo', 'São Paulo'), ('Paraná', 'Paraná'), ('Santa Catarina', 'Santa Catarina'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Mato Grosso', 'Mato Grosso'), ('Goiás', 'Goiás'), ('Distrito Federal', 'Distrito Federal')], max_length=100)),
                ('pais', models.CharField(help_text='EX.: BR', max_length=2, verbose_name='País')),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='EX.:nome-segundo', max_length=250)),
                ('cpf', models.CharField(help_text='EX.: 99999999999', max_length=11)),
                ('telefone1', models.CharField(help_text='EX.:99999999999999', max_length=14)),
                ('telefone2', models.CharField(blank=True, help_text='EX.:9999999999999', max_length=14, null=True)),
                ('img', models.ImageField(blank=True, help_text='Tamanho máximo 50x50', null=True, upload_to='', verbose_name='Imagem')),
                ('placa_veiculo', models.CharField(help_text='EX.: AAA-9999', max_length=8, verbose_name='Placa do Veículo')),
                ('endereco', models.ManyToManyField(to='delivery.Endereco')),
                ('filiado', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_entregador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entregadores',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qntItensTotal', models.IntegerField(blank=True, null=True)),
                ('status_pagamento', models.CharField(blank=True, choices=[('1', 'Pagamento Pendente'), ('2', 'Pagamento Realizado')], max_length=50, null=True)),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_pedido', models.BooleanField(default=False)),
                ('entrega', models.CharField(choices=[('1', 'Preparando'), ('2', 'A Caminho'), ('3', 'Entregue')], max_length=50)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='getCliente', to='delivery.Cliente')),
                ('endereco_entrega', models.ManyToManyField(blank=True, null=True, to='delivery.Endereco')),
                ('entregador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Entregador')),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Pagamento')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria_produto', models.CharField(choices=[('doce', 'Doces'), ('salgados', 'Salgados'), ('bebidas', 'Bebidas')], max_length=50, verbose_name='Categoria')),
                ('observacoes', models.TextField()),
                ('data_validade', models.DateTimeField()),
                ('peso', models.DecimalField(decimal_places=3, help_text='(g)', max_digits=5)),
                ('img', models.ImageField(blank=True, help_text='Tamanho máximo 50x50', null=True, upload_to='', verbose_name='Imagem')),
                ('restaurante', models.ManyToManyField(related_name='getDeliverys', to='delivery.Delivery')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_itens', models.IntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Pedido')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getEnderecos', to='delivery.Endereco'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='getDelivery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ManyToManyField(to='delivery.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='getCliente', to=settings.AUTH_USER_MODEL),
        ),
    ]
