# Generated by Django 2.2.7 on 2019-11-18 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='EX.:nome-sobrenome', max_length=250)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cpf', models.CharField(help_text='EX.: 99999999999', max_length=11)),
                ('telefone_celular', models.CharField(help_text='EX.:99999999999999', max_length=14)),
                ('telefone_fixo', models.CharField(blank=True, help_text='EX.:9999999999999', max_length=13, null=True)),
                ('idade', models.IntegerField()),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone_celular', models.CharField(help_text='EX.:99999999999999', max_length=14)),
                ('telefone_fixo', models.CharField(blank=True, help_text='EX.:9999999999999', max_length=13, null=True)),
                ('cnpj', models.CharField(help_text='99.999.999/9999-99', max_length=18)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
