# Generated by Django 2.2.7 on 2019-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_ativo',
            field=models.BooleanField(default=1, verbose_name='Ativo'),
            preserve_default=False,
        ),
    ]
