# Generated by Django 2.2.7 on 2019-12-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(blank=True, choices=[('1', 'Preparando'), ('2', 'A Caminho'), ('3', 'Entregue')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status_pedido',
            field=models.BooleanField(default=False, verbose_name='Foi Finalizdo?'),
        ),
    ]
