# Generated by Django 2.2.7 on 2019-12-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_pagamento',
            field=models.CharField(blank=True, choices=[('1', 'Pagamento Pendente'), ('2', 'Pagamento Realizado')], max_length=50, null=True),
        ),
    ]
