# Generated by Django 2.2.7 on 2019-12-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateTimeField(help_text='DD/MM/AAAA', verbose_name='Data de Validade'),
        ),
    ]
