# Generated by Django 2.2.7 on 2019-12-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191207_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='id_delivery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
        ),
    ]
