# Generated by Django 2.2.7 on 2019-12-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_is_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='is_ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
