# Generated by Django 2.2.7 on 2019-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20191209_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_validade',
            field=models.DateTimeField(help_text='EX.: AAAA-MM-DD HH:MM', verbose_name='Data de Validade'),
        ),
    ]
