# Generated by Django 2.2.7 on 2019-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=1, help_text='EX.:arroz-tio', max_length=250),
            preserve_default=False,
        ),
    ]
