# Generated by Django 2.2.7 on 2019-12-02 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191202_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
        ),
    ]
