# Generated by Django 2.2.7 on 2019-12-09 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191209_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='getDeliverys', to='delivery.Delivery'),
            preserve_default=False,
        ),
    ]
