# Generated by Django 2.2.7 on 2019-12-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20191208_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtopedido',
            name='id_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getIdDelivery', to='delivery.Delivery'),
        ),
    ]
