# Generated by Django 2.2.7 on 2019-12-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20191209_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='restaurante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='getDeliverys', to='delivery.Delivery'),
        ),
    ]
