# Generated by Django 2.2.7 on 2019-11-19 11:22

import delivery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_produto_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='produtos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='id_produto',
            field=models.CharField(default=1, max_length=255, verbose_name=delivery.models.Produto.get_pk),
            preserve_default=False,
        ),
    ]
