# Generated by Django 2.2.7 on 2019-12-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_auto_20191202_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
