# Generated by Django 2.2.7 on 2019-11-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20191119_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='finalizado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
