# Generated by Django 2.2.7 on 2019-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_produto_qnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ManyToManyField(blank=True, null=True, to='delivery.Endereco'),
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='entregador',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entregador',
            field=models.ManyToManyField(blank=True, null=True, to='delivery.Entregador'),
        ),
    ]
