# Generated by Django 2.2.7 on 2019-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_auto_20191209_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ManyToManyField(related_name='getDeliverys', to='delivery.Delivery'),
        ),
    ]
