# Generated by Django 2.2.7 on 2019-11-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20191119_0825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrinho',
        ),
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
