# Generated by Django 2.2.7 on 2019-12-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_auto_20191209_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregador',
            name='img',
        ),
        migrations.RemoveField(
            model_name='entregador',
            name='user',
        ),
    ]
