# Generated by Django 2.2.7 on 2019-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20191209_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='telefone1',
            field=models.CharField(help_text='EX.:(99)99999-9999', max_length=14),
        ),
        migrations.AlterField(
            model_name='entregador',
            name='telefone2',
            field=models.CharField(blank=True, help_text='EX.:(87)3333-3333', max_length=13, null=True),
        ),
    ]
