# Generated by Django 2.2.7 on 2019-11-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery', '0007_auto_20191119_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='EX.:nome-sobrenome', max_length=250)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('cpf', models.CharField(help_text='EX.: 99999999999', max_length=11)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_restaurante', models.CharField(help_text='Nome do Delivery: ', max_length=100)),
                ('cnpj', models.CharField(help_text='99.999.999/9999-99', max_length=18, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Entregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(help_text='EX.: 99999999999', max_length=11)),
                ('placa_veiculo', models.CharField(help_text='EX.: AAA-9999', max_length=8, verbose_name='Placa do Veículo')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('1', 'Pagamento Pendente'), ('2', 'Pagamento Realizado')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_itens', models.IntegerField(blank=True, null=True)),
                ('entregador', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery.Entregador')),
                ('pagamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_celular', models.CharField(help_text='EX.:99999999999999', max_length=14)),
                ('telefone_fixo', models.CharField(blank=True, help_text='EX.:9999999999999', max_length=13, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='img',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.CharField(help_text='EX.: BR', max_length=2, verbose_name='País'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.AddField(
            model_name='entregador',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
        ),
        migrations.AddField(
            model_name='entregador',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Usuario'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ManyToManyField(to='delivery.Endereco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.Usuario'),
        ),
        migrations.AddField(
            model_name='produto',
            name='pedido',
            field=models.ManyToManyField(blank=True, to='delivery.Pedido'),
        ),
        migrations.AddField(
            model_name='produto',
            name='restaurante',
            field=models.ManyToManyField(to='delivery.Delivery'),
        ),
    ]
