# Generated by Django 2.2.7 on 2019-12-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_auto_20191202_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('11', 'Rondônia'), ('12', 'Acre'), ('13', 'Amazonas'), ('14', 'Roraima'), ('15', 'Pará'), ('16', 'Amapá'), ('17', 'Tocantins'), ('21', 'Maranhão'), ('22', 'Piauí'), ('23', 'Ceará'), ('24', 'Rio Grande do Norte'), ('25', 'Paraíba'), ('26', 'Pernambuco'), ('27', 'Alagoas'), ('28', 'Sergipe'), ('29', 'Bahia'), ('31', 'Minas Gerais'), ('32', 'Espírito Santo'), ('33', 'Rio de Janeiro'), ('35', 'São Paulo'), ('41', 'Paraná'), ('42', 'Santa Catarina'), ('43', 'Rio Grande do Sul'), ('50', 'Mato Grosso do Sul'), ('51', 'Mato Grosso'), ('52', 'Goiás'), ('53', 'Distrito Federal')], max_length=100),
        ),
    ]
