# Generated by Django 2.2.7 on 2019-11-26 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_auto_20191125_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='endereco_entrega',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='status_pedido',
            field=models.BooleanField(default=False),
        ),
    ]
