# Generated by Django 2.2.7 on 2019-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20191126_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefone_celular',
            new_name='telefone_1',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone_fixo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone_2',
            field=models.CharField(blank=True, help_text='EX.:9999999999999', max_length=14, null=True),
        ),
    ]
