# Generated by Django 2.2.7 on 2019-12-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20191209_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='filiado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='getFiliados', to='delivery.Delivery'),
        ),
    ]
