# Generated by Django 2.2.7 on 2019-12-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_auto_20191203_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('Rondônia', 'Rondônia'), ('Acre', 'Acre'), ('Amazonas', 'Amazonas'), ('Roraima', 'Roraima'), ('Pará', 'Pará'), ('Amapá', 'Amapá'), ('Tocantins', 'Tocantins'), ('Maranhão', 'Maranhão'), ('Piauí', 'Piauí'), ('Ceará', 'Ceará'), ('Rio Grande do Norte', 'Rio Grande do Norte'), ('Paraíba', 'Paraíba'), ('Pernambuco', 'Pernambuco'), ('Alagoas', 'Alagoas'), ('Sergipe', 'Sergipe'), ('Bahia', 'Bahia'), ('Minas Gerais', 'Minas Gerais'), ('Espírito Santo', 'Espírito Santo'), ('Rio de Janeiro', 'Rio de Janeiro'), ('São Paulo', 'São Paulo'), ('Paraná', 'Paraná'), ('Santa Catarina', 'Santa Catarina'), ('Rio Grande do Sul', 'Rio Grande do Sul'), ('Mato Grosso do Sul', 'Mato Grosso do Sul'), ('Mato Grosso', 'Mato Grosso'), ('Goiás', 'Goiás'), ('Distrito Federal', 'Distrito Federal')], max_length=100),
        ),
    ]
