# Generated by Django 2.2.7 on 2019-11-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_auto_20191126_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='slug',
            field=models.SlugField(default=1, help_text='EX.:nome-segundo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entregador',
            name='slug',
            field=models.SlugField(default=1, help_text='EX.:nome-segundo', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(choices=[('1', 'Preparando'), ('2', 'A Caminho'), ('3', 'Entregue')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(help_text='EX.:nome-segundo', max_length=250),
        ),
    ]
