# Generated by Django 2.2.7 on 2019-11-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_auto_20191126_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='entregador',
            options={'verbose_name_plural': 'Entregadores'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='entregador',
            name='filiado',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='delivery.Delivery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img',
            field=models.ImageField(default=1, height_field=70, help_text='Tamanho máximo 50x50', upload_to='', verbose_name='Imagem', width_field=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='img',
            field=models.ImageField(default=1, height_field=70, help_text='Tamanho máximo 50x50', upload_to='', verbose_name='Imagem', width_field=70),
            preserve_default=False,
        ),
    ]
