# Generated by Django 2.2.7 on 2019-11-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0013_auto_20191126_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(help_text='Tamanho máximo 50x50', upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='img',
            field=models.ImageField(help_text='Tamanho máximo 50x50', upload_to='', verbose_name='Imagem'),
        ),
    ]
