# Generated by Django 2.2.7 on 2019-11-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0014_auto_20191126_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(help_text='EX.:nome-segundo', max_length=250),
        ),
    ]
