# Generated by Django 2.2.7 on 2019-11-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_auto_20191127_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, help_text='EX.:nome-segundo', max_length=250, null=True),
        ),
    ]
