# Generated by Django 2.2.7 on 2019-11-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_auto_20191128_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
            preserve_default=False,
        ),
    ]
