# Generated by Django 2.2.7 on 2019-11-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20191128_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='delivery.Endereco'),
        ),
    ]
