# Generated by Django 2.2.7 on 2019-12-01 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20191128_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_usuarios', to='delivery.Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
