# Generated by Django 2.2.7 on 2019-12-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0022_auto_20191201_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(choices=[('refeicao', 'Refeição'), ('bebida', 'Bebida'), ('sobremesas', 'Sobremesas')], default=1, max_length=50, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
