# Generated by Django 2.2.7 on 2019-12-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_auto_20191201_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='obsevacoes',
            new_name='observacoes',
        ),
        migrations.AlterField(
            model_name='produto',
            name='restaurante',
            field=models.ManyToManyField(related_name='get_deliverys', to='delivery.Delivery'),
        ),
    ]
