# Generated by Django 2.2.7 on 2019-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_auto_20191201_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='peso',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
